sonar.projectKey=api_gateway
sonar.projectName=Console Shop — API Gateway
sonar.projectVersion=1.0

sonar.sources=internal,cmd
sonar.tests=internal
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=test-report.xml

# Exclude infra/generated code from analysis
sonar.exclusions=cmd/**,**/*_mock.go,**/mock/**

sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarqube.lboevset.com
